---
name: epel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  push:
    paths:
      - 'roles/epel/**'
      - 'molecule/epel/**'
      - '.github/workflows/role_epel.yml'
  pull_request:
    paths:
      - 'roles/epel/**'
      - 'molecule/epel/**'
      - '.github/workflows/role_epel.yml'
